# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellcardmanagementapis.api_helper import APIHelper


class AutoRenewCardResponseDataItems(object):

    """Implementation of the 'AutoRenewCardResponseDataItems' model.

    Attributes:
        auto_renew_reference_id (int): CardId and PAN of the card. ;(
            Semicolon is used as delimiter.
        card_id_and_pan (str): Reference number for each individual auto renew
            card in the order.
        panid (float): PANID of the card

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "auto_renew_reference_id": 'AutoRenewReferenceId',
        "card_id_and_pan": 'CardIdAndPAN',
        "panid": 'PANID'
    }

    _optionals = [
        'auto_renew_reference_id',
        'card_id_and_pan',
        'panid',
    ]

    _nullables = [
        'auto_renew_reference_id',
        'card_id_and_pan',
        'panid',
    ]

    def __init__(self,
                 auto_renew_reference_id=APIHelper.SKIP,
                 card_id_and_pan=APIHelper.SKIP,
                 panid=APIHelper.SKIP):
        """Constructor for the AutoRenewCardResponseDataItems class"""

        # Initialize members of the class
        if auto_renew_reference_id is not APIHelper.SKIP:
            self.auto_renew_reference_id = auto_renew_reference_id 
        if card_id_and_pan is not APIHelper.SKIP:
            self.card_id_and_pan = card_id_and_pan 
        if panid is not APIHelper.SKIP:
            self.panid = panid 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        auto_renew_reference_id = dictionary.get("AutoRenewReferenceId") if "AutoRenewReferenceId" in dictionary.keys() else APIHelper.SKIP
        card_id_and_pan = dictionary.get("CardIdAndPAN") if "CardIdAndPAN" in dictionary.keys() else APIHelper.SKIP
        panid = dictionary.get("PANID") if "PANID" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(auto_renew_reference_id,
                   card_id_and_pan,
                   panid)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'auto_renew_reference_id={(self.auto_renew_reference_id if hasattr(self, "auto_renew_reference_id") else None)!r}, '
                f'card_id_and_pan={(self.card_id_and_pan if hasattr(self, "card_id_and_pan") else None)!r}, '
                f'panid={(self.panid if hasattr(self, "panid") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'auto_renew_reference_id={(self.auto_renew_reference_id if hasattr(self, "auto_renew_reference_id") else None)!s}, '
                f'card_id_and_pan={(self.card_id_and_pan if hasattr(self, "card_id_and_pan") else None)!s}, '
                f'panid={(self.panid if hasattr(self, "panid") else None)!s})')
