# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardDetailAutoRenewEnum(object):

    """Implementation of the 'CardDetailAutoRenew' enum.

    Whether to reissue card automatically when nearing the expiry. 
    Allowed values: -
    1.    As per card type setting (Default).
    2.    Card will be Reissued when nearing its expiry date.
    3.    Card will not be Reissued.

    Attributes:
        ENUM_1: The enum member of type int.
        ENUM_2: The enum member of type int.
        ENUM_3: The enum member of type int.

    """
    ENUM_1 = 1

    ENUM_2 = 2

    ENUM_3 = 3

