# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardDetailsResponseLocalPOSLanguageCodeEnum(object):

    """Implementation of the 'CardDetailsResponseLocalPOSLanguageCode' enum.

    POS language code. Language code:
      * `deu` - German
      * `fra` - French
      * `bul` - Bulgarian
      * `hrv` - Croatian
      * `ces` - Czech
      * `dan` - Danish
      * `fin` - Finnish
      * `eng` - English
      * `ell` - Greek
      * `zho` - Chinese
      * `hun` - Hungarian
      * `ita` - Italian
      * `ltz` - Luxembourgish
      * `msa` - Malay
      * `nld` - Dutch
      * `nob` - Norwegian, Bokmal
      * `urd` - Urdu
      * `pol` - Polish
      * `por` - Portuguese
      * `ron` - Romanian
      * `rus` - Russian
      * `slk` - Slovak
      * `slv` - Slovenian
      * `spa` - Spanish
      * `swe` - Swedish
      * `tur` - Turkish
      * `tha` - Thai
      * `fil` - Filipino
      * `est` - Estonian
      * `lav` - Latvian
      * `lit` - Lithuanian

    Attributes:
        DEU: TODO: type description here.
        FRA: TODO: type description here.
        BUL: TODO: type description here.
        HRV: TODO: type description here.
        CES: TODO: type description here.
        DAN: TODO: type description here.
        FIN: TODO: type description here.
        ENG: TODO: type description here.
        ELL: TODO: type description here.
        ZHO: TODO: type description here.
        HUN: TODO: type description here.
        ITA: TODO: type description here.
        LTZ: TODO: type description here.
        MSA: TODO: type description here.
        NLD: TODO: type description here.
        NOB: TODO: type description here.
        URD: TODO: type description here.
        POL: TODO: type description here.
        POR: TODO: type description here.
        RON: TODO: type description here.
        RUS: TODO: type description here.
        SLK: TODO: type description here.
        SLV: TODO: type description here.
        SPA: TODO: type description here.
        SWE: TODO: type description here.
        TUR: TODO: type description here.
        THA: TODO: type description here.
        FIL: TODO: type description here.
        EST: TODO: type description here.
        LAV: TODO: type description here.
        LIT: TODO: type description here.

    """
    DEU = 'deu'

    FRA = 'fra'

    BUL = 'bul'

    HRV = 'hrv'

    CES = 'ces'

    DAN = 'dan'

    FIN = 'fin'

    ENG = 'eng'

    ELL = 'ell'

    ZHO = 'zho'

    HUN = 'hun'

    ITA = 'ita'

    LTZ = 'ltz'

    MSA = 'msa'

    NLD = 'nld'

    NOB = 'nob'

    URD = 'urd'

    POL = 'pol'

    POR = 'por'

    RON = 'ron'

    RUS = 'rus'

    SLK = 'slk'

    SLV = 'slv'

    SPA = 'spa'

    SWE = 'swe'

    TUR = 'tur'

    THA = 'tha'

    FIL = 'fil'

    EST = 'est'

    LAV = 'lav'

    LIT = 'lit'

