# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardDetailsResponseStatusIdEnum(object):

    """Implementation of the 'CardDetailsResponseStatusId' enum.

    Possible Id’s and description:
    * 1  Active
    * 7  Blocked Card
    * 8  Expired
    * 9  Cancelled
    * 10  New
    * 23  Pending Renewal
    * 31  Replaced
    * 41  Temporary Block (Customer)
    * 42  Temporary Block (Shell)
    * 43  Fraud
    * 101 Active (Block in progress) *
    * 102 Blocked Card (Unblock in progress) *
    * 103 Active (Cancel in progress) *
    * 104 Active (Marked as damaged) *
    * 105 New (Cancel as damaged) *
    * 106 Active(Scheduled for block) ”#
    * 107 Blocked Card(Scheduled for unblock)*#
    * 108 Blocked Card (Cancel in progress) *
    > Note:
    •  Items marked with * are intermediate statuses  to indicate that there
    are pending requests in progress. , The response can contain these
    intermediate statuses only if the IncludeIntermediateStatus flag is true.
    •  The placeholder “<Shell Card Platform Status>” in the items marked with
    # will be replaced with the Shell Card Platform status description. E.g.,
    “Active (Scheduled for block)”

    Attributes:
        ENUM_1: The enum member of type int.
        ENUM_7: The enum member of type int.
        ENUM_8: The enum member of type int.
        ENUM_9: The enum member of type int.
        ENUM_10: The enum member of type int.
        ENUM_23: The enum member of type int.
        ENUM_31: The enum member of type int.
        ENUM_41: The enum member of type int.
        ENUM_42: The enum member of type int.
        ENUM_43: The enum member of type int.
        ENUM_101: The enum member of type int.
        ENUM_102: The enum member of type int.
        ENUM_103: The enum member of type int.
        ENUM_104: The enum member of type int.
        ENUM_105: The enum member of type int.
        ENUM_106: The enum member of type int.
        ENUM_107: The enum member of type int.
        ENUM_108: The enum member of type int.

    """
    ENUM_1 = 1

    ENUM_7 = 7

    ENUM_8 = 8

    ENUM_9 = 9

    ENUM_10 = 10

    ENUM_23 = 23

    ENUM_31 = 31

    ENUM_41 = 41

    ENUM_42 = 42

    ENUM_43 = 43

    ENUM_101 = 101

    ENUM_102 = 102

    ENUM_103 = 103

    ENUM_104 = 104

    ENUM_105 = 105

    ENUM_106 = 106

    ENUM_107 = 107

    ENUM_108 = 108

