# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardDetailsResponsePINTypeEnum(object):

    """Implementation of the 'CardDetailsResponsePINType' enum.

    PIN type:
      * `Card` - Card PIN
      * `Fleet` - Fleet PIN

    Attributes:
        CARD: TODO: type description here.
        FLEET: TODO: type description here.

    """
    CARD = 'Card'

    FLEET = 'Fleet'

