# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CardDetailsResponseRenewedCardReissueSettingEnum(object):

    """Implementation of the 'CardDetailsResponseRenewedCardReissueSetting' enum.

    Reissue setting of the renewed new card. Reissue Setting:
      * `True` - Card will be sent to production
      * `False` - Parent Card is Dormant or the Card is not to be produced

    Attributes:
        TRUE: TODO: type description here.
        FALSE: TODO: type description here.

    """
    ENUM_TRUE = 'True'

    ENUM_FALSE = 'False'

