# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellcardmanagementapis.api_helper import APIHelper


class CreateBundleResponseDataItemsCardsItems(object):

    """Implementation of the 'CreateBundleResponseDataItemsCardsItems' model.

    TODO: type model description here.

    Attributes:
        pan (str): Card PAN.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pan": 'PAN'
    }

    _optionals = [
        'pan',
    ]

    def __init__(self,
                 pan=APIHelper.SKIP):
        """Constructor for the CreateBundleResponseDataItemsCardsItems class"""

        # Initialize members of the class
        if pan is not APIHelper.SKIP:
            self.pan = pan 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        pan = dictionary.get("PAN") if dictionary.get("PAN") else APIHelper.SKIP
        # Return an object of this model
        return cls(pan)
