# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellcardmanagementapis.api_helper import APIHelper


class CreateCardGroupResponseErrorCardsItems(object):

    """Implementation of the 'CreateCardGroupResponseErrorCardsItems' model.

    TODO: type model description here.

    Attributes:
        card_id (int): Card Id of the card.
        pan (str): PAN of the card.
        error_code (str): Error code for validation failure.
        error_description (str): Description of validation failure.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "card_id": 'CardId',
        "pan": 'PAN',
        "error_code": 'ErrorCode',
        "error_description": 'ErrorDescription'
    }

    _optionals = [
        'card_id',
        'pan',
        'error_code',
        'error_description',
    ]

    def __init__(self,
                 card_id=APIHelper.SKIP,
                 pan=APIHelper.SKIP,
                 error_code=APIHelper.SKIP,
                 error_description=APIHelper.SKIP):
        """Constructor for the CreateCardGroupResponseErrorCardsItems class"""

        # Initialize members of the class
        if card_id is not APIHelper.SKIP:
            self.card_id = card_id 
        if pan is not APIHelper.SKIP:
            self.pan = pan 
        if error_code is not APIHelper.SKIP:
            self.error_code = error_code 
        if error_description is not APIHelper.SKIP:
            self.error_description = error_description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        card_id = dictionary.get("CardId") if dictionary.get("CardId") else APIHelper.SKIP
        pan = dictionary.get("PAN") if dictionary.get("PAN") else APIHelper.SKIP
        error_code = dictionary.get("ErrorCode") if dictionary.get("ErrorCode") else APIHelper.SKIP
        error_description = dictionary.get("ErrorDescription") if dictionary.get("ErrorDescription") else APIHelper.SKIP
        # Return an object of this model
        return cls(card_id,
                   pan,
                   error_code,
                   error_description)
