# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellcardmanagementapis.api_helper import APIHelper
from shellcardmanagementapis.models.create_bundle_response_data_items import CreateBundleResponseDataItems
from shellcardmanagementapis.models.error_details import ErrorDetails


class CreateBundleResponse(object):

    """Implementation of the 'CreateBundleResponse' model.

    TODO: type model description here.

    Attributes:
        request_id (str): Request Id
        status (str): Response status
        data (List[CreateBundleResponseDataItems]): TODO: type description
            here.
        errors (List[ErrorDetails]): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_id": 'RequestId',
        "status": 'Status',
        "data": 'Data',
        "errors": 'Errors'
    }

    _optionals = [
        'request_id',
        'status',
        'data',
        'errors',
    ]

    def __init__(self,
                 request_id=APIHelper.SKIP,
                 status=APIHelper.SKIP,
                 data=APIHelper.SKIP,
                 errors=APIHelper.SKIP):
        """Constructor for the CreateBundleResponse class"""

        # Initialize members of the class
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id 
        if status is not APIHelper.SKIP:
            self.status = status 
        if data is not APIHelper.SKIP:
            self.data = data 
        if errors is not APIHelper.SKIP:
            self.errors = errors 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        request_id = dictionary.get("RequestId") if dictionary.get("RequestId") else APIHelper.SKIP
        status = dictionary.get("Status") if dictionary.get("Status") else APIHelper.SKIP
        data = None
        if dictionary.get('Data') is not None:
            data = [CreateBundleResponseDataItems.from_dictionary(x) for x in dictionary.get('Data')]
        else:
            data = APIHelper.SKIP
        errors = None
        if dictionary.get('Errors') is not None:
            errors = [ErrorDetails.from_dictionary(x) for x in dictionary.get('Errors')]
        else:
            errors = APIHelper.SKIP
        # Return an object of this model
        return cls(request_id,
                   status,
                   data,
                   errors)
