# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ProductAllOf0(object):

    """Implementation of the 'ProductAllOf0' model.

    TODO: type model description here.

    Attributes:
        global_product_code (str): The productCode returned by the Gateway
            API. Example: 021
        description (str): The description returned by the Gateway API.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "global_product_code": 'GlobalProductCode',
        "description": 'Description'
    }

    _nullables = [
        'global_product_code',
        'description',
    ]

    def __init__(self,
                 global_product_code=None,
                 description=None):
        """Constructor for the ProductAllOf0 class"""

        # Initialize members of the class
        self.global_product_code = global_product_code 
        self.description = description 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        global_product_code = dictionary.get("GlobalProductCode") if dictionary.get("GlobalProductCode") else None
        description = dictionary.get("Description") if dictionary.get("Description") else None
        # Return an object of this model
        return cls(global_product_code,
                   description)
