# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellcardmanagementapis.api_helper import APIHelper
from shellcardmanagementapis.models.search_card_response_restrictions import SearchCardResponseRestrictions


class RestrictionSearchCardResponseDataItems(object):

    """Implementation of the 'RestrictionSearchCardResponseDataItems' model.

    TODO: type model description here.

    Attributes:
        bundle_id (int): Bundle Id associated with card
        restrictions (SearchCardResponseRestrictions): TODO: type description
            here.
        restriction_currency_code (str): ISO currency code of the country.
        restriction_currency_symbol (str): Currency symbol of the country.
        account_id (int): Account ID
        account_name (str): Account Name
        account_number (str): Account Number
        account_short_name (str): AccountShortName
        card_id (int): Unique Card
        card_type_code (str): ISO code of the card i.e. first 7 digits of the
            PAN
        card_type_id (int): Card Type ID  Example Id & Description:  1 -
            Philippines CRT 7077861  2- Philippines Fleet 7002861  5-SHELL
            FLEET- HONG KONG 7002821  6-SHELL NHF- HONG KONG 7002821  7-SHELL
            CRT- HONG KONG 7077821
        card_type_name (str): Card Type Name  Example Id & Description:  1 -
            Philippines CRT 7077861  2- Philippines Fleet 7002861  5-SHELL
            FLEET- HONG KONG 7002821  6-SHELL NHF- HONG KONG 7002821  7-SHELL
            CRT- HONG KONG 7077821
        col_co_currency_code (str): ISO currency code of the country
        col_co_currency_symbol (str): Currency symbol of the country
        currency_code (str): ISO currency code of the Customer Currency
        currency_symbol (str): Currency symbol of the Customer Currency Code
        driver_name (str): Driver name
        expiry_date (str): Expiry date of the card   Format: yyyyMMdd
        is_crt (bool): True if it is a CRT type card, else false
        is_fleet (bool): True if it is a Fleet type card, else false
        is_international (bool): True if it is an international card, else
            false
        is_national (bool): True if it is a national card, else false
        is_partner_sites_included (bool): True if it is allowed at all partner
            sites, else false
        is_shell_sites_only (bool): True if it is only allowed at Shell sites,
            else false
        issue_date (str): Issue date  Format: yyyyMMdd
        issue_number (int): Issue Number
        is_superseded (bool): True if a new card is issued with the same PAN,
            else false
        is_virtual_card (bool): True if it is a virtual card, else false
        pan (str): Card PAN
        purchase_category_code (str): Purchase category code   Example:   0 -
            All Fuels (without VP) and Lubricants  1 - FuelSave only  2 -
            FuelSave and Lubricants  3 - No Restrictions  4 - VP and FuelSave 
            5 - Diesel ONLY  6 - Diesel and Lubricants  7 - VP and Lubricants 
            8 - VP and FuelSave and Lubricants
        purchase_category_id (int): Purchase category Id
        purchase_category_name (str): Purchase category name   Example:   0 -
            All Fuels (without VP) and Lubricants  1 - FuelSave only  2 -
            FuelSave and Lubricants  3 - No Restrictions  4 - VP and FuelSave 
            5 - Diesel ONLY  6 - Diesel and Lubricants  7 - VP and Lubricants 
            8 - VP and FuelSave and Lubricants
        status_description (str): Status Description (Active, Temporarily
            Blocked, etc.,)
        status_id (int): Card Status id
        vrn (str): Vehicle registration number
        medium_type_id (int): Id of the medium type identifier.    Example:
            1,2,4    Full list below:  1 - Fuel Card  2 - Fuel Card with EV  4
            - Fuel Card and Key fob Card  5 - Key fob  6 - Virtual Card  7 -
            NPII Token  8 – Smartpay
        medium_type (str): Name of the medium type identifier.    Example:
            Fuel Card, Fuel Card with EV, Key fob    Full list below:  1 -
            Fuel Card  2 - Fuel Card with EV  4 - Fuel Card and Key fob Card 
            5 - Key fob  6 - Virtual Card  7 - NPII Token  8 - Smartpay

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "bundle_id": 'BundleId',
        "restrictions": 'Restrictions',
        "restriction_currency_code": 'RestrictionCurrencyCode',
        "restriction_currency_symbol": 'RestrictionCurrencySymbol',
        "account_id": 'AccountId',
        "account_name": 'AccountName',
        "account_number": 'AccountNumber',
        "account_short_name": 'AccountShortName',
        "card_id": 'CardId',
        "card_type_code": 'CardTypeCode',
        "card_type_id": 'CardTypeId',
        "card_type_name": 'CardTypeName',
        "col_co_currency_code": 'ColCoCurrencyCode',
        "col_co_currency_symbol": 'ColCoCurrencySymbol',
        "currency_code": 'CurrencyCode',
        "currency_symbol": 'CurrencySymbol',
        "driver_name": 'DriverName',
        "expiry_date": 'ExpiryDate',
        "is_crt": 'IsCRT',
        "is_fleet": 'IsFleet',
        "is_international": 'IsInternational',
        "is_national": 'IsNational',
        "is_partner_sites_included": 'IsPartnerSitesIncluded',
        "is_shell_sites_only": 'IsShellSitesOnly',
        "issue_date": 'IssueDate',
        "issue_number": 'IssueNumber',
        "is_superseded": 'IsSuperseded',
        "is_virtual_card": 'IsVirtualCard',
        "pan": 'PAN',
        "purchase_category_code": 'PurchaseCategoryCode',
        "purchase_category_id": 'PurchaseCategoryId',
        "purchase_category_name": 'PurchaseCategoryName',
        "status_description": 'StatusDescription',
        "status_id": 'StatusId',
        "vrn": 'VRN',
        "medium_type_id": 'MediumTypeID',
        "medium_type": 'MediumType'
    }

    _optionals = [
        'bundle_id',
        'restrictions',
        'restriction_currency_code',
        'restriction_currency_symbol',
        'account_id',
        'account_name',
        'account_number',
        'account_short_name',
        'card_id',
        'card_type_code',
        'card_type_id',
        'card_type_name',
        'col_co_currency_code',
        'col_co_currency_symbol',
        'currency_code',
        'currency_symbol',
        'driver_name',
        'expiry_date',
        'is_crt',
        'is_fleet',
        'is_international',
        'is_national',
        'is_partner_sites_included',
        'is_shell_sites_only',
        'issue_date',
        'issue_number',
        'is_superseded',
        'is_virtual_card',
        'pan',
        'purchase_category_code',
        'purchase_category_id',
        'purchase_category_name',
        'status_description',
        'status_id',
        'vrn',
        'medium_type_id',
        'medium_type',
    ]

    _nullables = [
        'restriction_currency_code',
        'restriction_currency_symbol',
        'account_id',
        'account_name',
        'account_number',
        'account_short_name',
        'card_id',
        'card_type_code',
        'card_type_id',
        'card_type_name',
        'col_co_currency_code',
        'col_co_currency_symbol',
        'currency_code',
        'currency_symbol',
        'driver_name',
        'expiry_date',
        'issue_date',
        'issue_number',
        'pan',
        'purchase_category_code',
        'purchase_category_id',
        'purchase_category_name',
        'status_description',
        'status_id',
        'vrn',
        'medium_type_id',
        'medium_type',
    ]

    def __init__(self,
                 bundle_id=APIHelper.SKIP,
                 restrictions=APIHelper.SKIP,
                 restriction_currency_code=APIHelper.SKIP,
                 restriction_currency_symbol=APIHelper.SKIP,
                 account_id=APIHelper.SKIP,
                 account_name=APIHelper.SKIP,
                 account_number=APIHelper.SKIP,
                 account_short_name=APIHelper.SKIP,
                 card_id=APIHelper.SKIP,
                 card_type_code=APIHelper.SKIP,
                 card_type_id=APIHelper.SKIP,
                 card_type_name=APIHelper.SKIP,
                 col_co_currency_code=APIHelper.SKIP,
                 col_co_currency_symbol=APIHelper.SKIP,
                 currency_code=APIHelper.SKIP,
                 currency_symbol=APIHelper.SKIP,
                 driver_name=APIHelper.SKIP,
                 expiry_date=APIHelper.SKIP,
                 is_crt=APIHelper.SKIP,
                 is_fleet=APIHelper.SKIP,
                 is_international=APIHelper.SKIP,
                 is_national=APIHelper.SKIP,
                 is_partner_sites_included=APIHelper.SKIP,
                 is_shell_sites_only=APIHelper.SKIP,
                 issue_date=APIHelper.SKIP,
                 issue_number=APIHelper.SKIP,
                 is_superseded=APIHelper.SKIP,
                 is_virtual_card=APIHelper.SKIP,
                 pan=APIHelper.SKIP,
                 purchase_category_code=APIHelper.SKIP,
                 purchase_category_id=APIHelper.SKIP,
                 purchase_category_name=APIHelper.SKIP,
                 status_description=APIHelper.SKIP,
                 status_id=APIHelper.SKIP,
                 vrn=APIHelper.SKIP,
                 medium_type_id=APIHelper.SKIP,
                 medium_type=APIHelper.SKIP):
        """Constructor for the RestrictionSearchCardResponseDataItems class"""

        # Initialize members of the class
        if bundle_id is not APIHelper.SKIP:
            self.bundle_id = bundle_id 
        if restrictions is not APIHelper.SKIP:
            self.restrictions = restrictions 
        if restriction_currency_code is not APIHelper.SKIP:
            self.restriction_currency_code = restriction_currency_code 
        if restriction_currency_symbol is not APIHelper.SKIP:
            self.restriction_currency_symbol = restriction_currency_symbol 
        if account_id is not APIHelper.SKIP:
            self.account_id = account_id 
        if account_name is not APIHelper.SKIP:
            self.account_name = account_name 
        if account_number is not APIHelper.SKIP:
            self.account_number = account_number 
        if account_short_name is not APIHelper.SKIP:
            self.account_short_name = account_short_name 
        if card_id is not APIHelper.SKIP:
            self.card_id = card_id 
        if card_type_code is not APIHelper.SKIP:
            self.card_type_code = card_type_code 
        if card_type_id is not APIHelper.SKIP:
            self.card_type_id = card_type_id 
        if card_type_name is not APIHelper.SKIP:
            self.card_type_name = card_type_name 
        if col_co_currency_code is not APIHelper.SKIP:
            self.col_co_currency_code = col_co_currency_code 
        if col_co_currency_symbol is not APIHelper.SKIP:
            self.col_co_currency_symbol = col_co_currency_symbol 
        if currency_code is not APIHelper.SKIP:
            self.currency_code = currency_code 
        if currency_symbol is not APIHelper.SKIP:
            self.currency_symbol = currency_symbol 
        if driver_name is not APIHelper.SKIP:
            self.driver_name = driver_name 
        if expiry_date is not APIHelper.SKIP:
            self.expiry_date = expiry_date 
        if is_crt is not APIHelper.SKIP:
            self.is_crt = is_crt 
        if is_fleet is not APIHelper.SKIP:
            self.is_fleet = is_fleet 
        if is_international is not APIHelper.SKIP:
            self.is_international = is_international 
        if is_national is not APIHelper.SKIP:
            self.is_national = is_national 
        if is_partner_sites_included is not APIHelper.SKIP:
            self.is_partner_sites_included = is_partner_sites_included 
        if is_shell_sites_only is not APIHelper.SKIP:
            self.is_shell_sites_only = is_shell_sites_only 
        if issue_date is not APIHelper.SKIP:
            self.issue_date = issue_date 
        if issue_number is not APIHelper.SKIP:
            self.issue_number = issue_number 
        if is_superseded is not APIHelper.SKIP:
            self.is_superseded = is_superseded 
        if is_virtual_card is not APIHelper.SKIP:
            self.is_virtual_card = is_virtual_card 
        if pan is not APIHelper.SKIP:
            self.pan = pan 
        if purchase_category_code is not APIHelper.SKIP:
            self.purchase_category_code = purchase_category_code 
        if purchase_category_id is not APIHelper.SKIP:
            self.purchase_category_id = purchase_category_id 
        if purchase_category_name is not APIHelper.SKIP:
            self.purchase_category_name = purchase_category_name 
        if status_description is not APIHelper.SKIP:
            self.status_description = status_description 
        if status_id is not APIHelper.SKIP:
            self.status_id = status_id 
        if vrn is not APIHelper.SKIP:
            self.vrn = vrn 
        if medium_type_id is not APIHelper.SKIP:
            self.medium_type_id = medium_type_id 
        if medium_type is not APIHelper.SKIP:
            self.medium_type = medium_type 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        bundle_id = dictionary.get("BundleId") if dictionary.get("BundleId") else APIHelper.SKIP
        restrictions = SearchCardResponseRestrictions.from_dictionary(dictionary.get('Restrictions')) if 'Restrictions' in dictionary.keys() else APIHelper.SKIP
        restriction_currency_code = dictionary.get("RestrictionCurrencyCode") if "RestrictionCurrencyCode" in dictionary.keys() else APIHelper.SKIP
        restriction_currency_symbol = dictionary.get("RestrictionCurrencySymbol") if "RestrictionCurrencySymbol" in dictionary.keys() else APIHelper.SKIP
        account_id = dictionary.get("AccountId") if "AccountId" in dictionary.keys() else APIHelper.SKIP
        account_name = dictionary.get("AccountName") if "AccountName" in dictionary.keys() else APIHelper.SKIP
        account_number = dictionary.get("AccountNumber") if "AccountNumber" in dictionary.keys() else APIHelper.SKIP
        account_short_name = dictionary.get("AccountShortName") if "AccountShortName" in dictionary.keys() else APIHelper.SKIP
        card_id = dictionary.get("CardId") if "CardId" in dictionary.keys() else APIHelper.SKIP
        card_type_code = dictionary.get("CardTypeCode") if "CardTypeCode" in dictionary.keys() else APIHelper.SKIP
        card_type_id = dictionary.get("CardTypeId") if "CardTypeId" in dictionary.keys() else APIHelper.SKIP
        card_type_name = dictionary.get("CardTypeName") if "CardTypeName" in dictionary.keys() else APIHelper.SKIP
        col_co_currency_code = dictionary.get("ColCoCurrencyCode") if "ColCoCurrencyCode" in dictionary.keys() else APIHelper.SKIP
        col_co_currency_symbol = dictionary.get("ColCoCurrencySymbol") if "ColCoCurrencySymbol" in dictionary.keys() else APIHelper.SKIP
        currency_code = dictionary.get("CurrencyCode") if "CurrencyCode" in dictionary.keys() else APIHelper.SKIP
        currency_symbol = dictionary.get("CurrencySymbol") if "CurrencySymbol" in dictionary.keys() else APIHelper.SKIP
        driver_name = dictionary.get("DriverName") if "DriverName" in dictionary.keys() else APIHelper.SKIP
        expiry_date = dictionary.get("ExpiryDate") if "ExpiryDate" in dictionary.keys() else APIHelper.SKIP
        is_crt = dictionary.get("IsCRT") if "IsCRT" in dictionary.keys() else APIHelper.SKIP
        is_fleet = dictionary.get("IsFleet") if "IsFleet" in dictionary.keys() else APIHelper.SKIP
        is_international = dictionary.get("IsInternational") if "IsInternational" in dictionary.keys() else APIHelper.SKIP
        is_national = dictionary.get("IsNational") if "IsNational" in dictionary.keys() else APIHelper.SKIP
        is_partner_sites_included = dictionary.get("IsPartnerSitesIncluded") if "IsPartnerSitesIncluded" in dictionary.keys() else APIHelper.SKIP
        is_shell_sites_only = dictionary.get("IsShellSitesOnly") if "IsShellSitesOnly" in dictionary.keys() else APIHelper.SKIP
        issue_date = dictionary.get("IssueDate") if "IssueDate" in dictionary.keys() else APIHelper.SKIP
        issue_number = dictionary.get("IssueNumber") if "IssueNumber" in dictionary.keys() else APIHelper.SKIP
        is_superseded = dictionary.get("IsSuperseded") if "IsSuperseded" in dictionary.keys() else APIHelper.SKIP
        is_virtual_card = dictionary.get("IsVirtualCard") if "IsVirtualCard" in dictionary.keys() else APIHelper.SKIP
        pan = dictionary.get("PAN") if "PAN" in dictionary.keys() else APIHelper.SKIP
        purchase_category_code = dictionary.get("PurchaseCategoryCode") if "PurchaseCategoryCode" in dictionary.keys() else APIHelper.SKIP
        purchase_category_id = dictionary.get("PurchaseCategoryId") if "PurchaseCategoryId" in dictionary.keys() else APIHelper.SKIP
        purchase_category_name = dictionary.get("PurchaseCategoryName") if "PurchaseCategoryName" in dictionary.keys() else APIHelper.SKIP
        status_description = dictionary.get("StatusDescription") if "StatusDescription" in dictionary.keys() else APIHelper.SKIP
        status_id = dictionary.get("StatusId") if "StatusId" in dictionary.keys() else APIHelper.SKIP
        vrn = dictionary.get("VRN") if "VRN" in dictionary.keys() else APIHelper.SKIP
        medium_type_id = dictionary.get("MediumTypeID") if "MediumTypeID" in dictionary.keys() else APIHelper.SKIP
        medium_type = dictionary.get("MediumType") if "MediumType" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(bundle_id,
                   restrictions,
                   restriction_currency_code,
                   restriction_currency_symbol,
                   account_id,
                   account_name,
                   account_number,
                   account_short_name,
                   card_id,
                   card_type_code,
                   card_type_id,
                   card_type_name,
                   col_co_currency_code,
                   col_co_currency_symbol,
                   currency_code,
                   currency_symbol,
                   driver_name,
                   expiry_date,
                   is_crt,
                   is_fleet,
                   is_international,
                   is_national,
                   is_partner_sites_included,
                   is_shell_sites_only,
                   issue_date,
                   issue_number,
                   is_superseded,
                   is_virtual_card,
                   pan,
                   purchase_category_code,
                   purchase_category_id,
                   purchase_category_name,
                   status_description,
                   status_id,
                   vrn,
                   medium_type_id,
                   medium_type)
