# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellcardmanagementapis.api_helper import APIHelper


class RestrictionSearchCardRequestFiltersCardsItems(object):

    """Implementation of the 'RestrictionSearchCardRequestFiltersCardsItems' model.

    TODO: type model description here.

    Attributes:
        pan (str): Card PAN.  Optional if CardId is given, else mandatory.  
            Note: PAN is ignored if CardId is given.
        card_id (int): Unique Card Id in GFN.  Optional if PAN is given, else
            mandatory.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pan": 'PAN',
        "card_id": 'CardId'
    }

    _optionals = [
        'pan',
        'card_id',
    ]

    def __init__(self,
                 pan=APIHelper.SKIP,
                 card_id=APIHelper.SKIP):
        """Constructor for the RestrictionSearchCardRequestFiltersCardsItems class"""

        # Initialize members of the class
        if pan is not APIHelper.SKIP:
            self.pan = pan 
        if card_id is not APIHelper.SKIP:
            self.card_id = card_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        pan = dictionary.get("PAN") if dictionary.get("PAN") else APIHelper.SKIP
        card_id = dictionary.get("CardId") if dictionary.get("CardId") else APIHelper.SKIP
        # Return an object of this model
        return cls(pan,
                   card_id)
