# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from shellcardmanagementapis.api_helper import APIHelper
from shellcardmanagementapis.models.error_details import ErrorDetails


class UpdateBundleResponse(object):

    """Implementation of the 'UpdateBundleResponse' model.

    TODO: type model description here.

    Attributes:
        request_id (str): API Request Id
        status (str): API Response Status
        errors (ErrorDetails): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "request_id": 'RequestId',
        "status": 'Status',
        "errors": 'Errors'
    }

    _optionals = [
        'request_id',
        'status',
        'errors',
    ]

    def __init__(self,
                 request_id=APIHelper.SKIP,
                 status=APIHelper.SKIP,
                 errors=APIHelper.SKIP):
        """Constructor for the UpdateBundleResponse class"""

        # Initialize members of the class
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id 
        if status is not APIHelper.SKIP:
            self.status = status 
        if errors is not APIHelper.SKIP:
            self.errors = errors 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if dictionary is None:
            return None

        # Extract variables from the dictionary
        request_id = dictionary.get("RequestId") if dictionary.get("RequestId") else APIHelper.SKIP
        status = dictionary.get("Status") if dictionary.get("Status") else APIHelper.SKIP
        errors = ErrorDetails.from_dictionary(dictionary.get('Errors')) if 'Errors' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(request_id,
                   status,
                   errors)
