# -*- coding: utf-8 -*-

"""
shellcardmanagementapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class UrlEnum(object):

    """Implementation of the 'url' enum.

    TODO: type enum description here.

    Attributes:
        ENUM_APITESTSHELLCOMTEST: TODO: type description here.
        ENUM_APISHELLCOM: TODO: type description here.

    """
    ENUM_APITESTSHELLCOMTEST = 'api-test.shell.com/test'

    ENUM_APISHELLCOM = 'api.shell.com'

